import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "path";
import { existsSync, readFileSync } from "node:fs";
import runtimeErrorOverlay from "@replit/vite-plugin-runtime-error-modal";

const port = Number(process.env.PORT) || 3000;
const basePath = process.env.BASE_PATH || "/";

/**
 * Emits AVIF + WebP siblings next to every JPG/JPEG/PNG asset that Vite
 * bundles. The siblings are pre-generated by `scripts/optimize-images.mjs`.
 * The output filename uses the same `[name]-[hash]` stem as the original so
 * the <Picture> component (which derives sibling URLs by swapping extensions)
 * resolves correctly in production builds.
 */
function emitImageSiblings(): Plugin {
  const IMG_EXT = /\.(jpe?g|png)$/i;
  return {
    name: "emit-image-siblings",
    apply: "build",
    generateBundle(_options, bundle) {
      for (const [fileName, asset] of Object.entries(bundle)) {
        if (asset.type !== "asset") continue;
        if (!IMG_EXT.test(fileName)) continue;
        const originalName = (asset as { name?: string }).name;
        if (!originalName) continue;
        const srcDir = path.resolve(import.meta.dirname, "..", "..", "attached_assets");
        const stem = originalName.replace(IMG_EXT, "");
        const fileStem = fileName.replace(IMG_EXT, "");
        for (const ext of [".avif", ".webp"] as const) {
          const sourcePath = path.join(srcDir, `${stem}${ext}`);
          if (!existsSync(sourcePath)) continue;
          this.emitFile({
            type: "asset",
            fileName: `${fileStem}${ext}`,
            source: readFileSync(sourcePath),
          });
        }
      }
    },
  };
}

export default defineConfig({
  base: basePath,
  plugins: [
    react(),
    tailwindcss(),
    runtimeErrorOverlay(),
    emitImageSiblings(),
    ...(process.env.NODE_ENV !== "production" &&
    process.env.REPL_ID !== undefined
      ? [
          await import("@replit/vite-plugin-cartographer").then((m) =>
            m.cartographer({
              root: path.resolve(import.meta.dirname, ".."),
            }),
          ),
          await import("@replit/vite-plugin-dev-banner").then((m) =>
            m.devBanner(),
          ),
        ]
      : []),
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "src"),
      "@assets": path.resolve(import.meta.dirname, "..", "..", "attached_assets"),
    },
    dedupe: ["react", "react-dom"],
  },
  root: path.resolve(import.meta.dirname),
  build: {
    outDir: path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (!id.includes("node_modules")) return;
          // Core React runtime — always needed, cached long-term
          if (
            id.includes("/react/") ||
            id.includes("/react-dom/") ||
            id.includes("/react-router") ||
            id.includes("/scheduler/")
          ) return "vendor-react";
          // Animation — large, changes independently of app code
          if (id.includes("/framer-motion/")) return "vendor-motion";
          // Server-state cache
          if (id.includes("/@tanstack/")) return "vendor-query";
          // Auth — updates on its own release cycle
          if (id.includes("/@clerk/")) return "vendor-clerk";
          // i18n
          if (id.includes("/i18next") || id.includes("/react-i18next/")) return "vendor-i18n";
        },
      },
    },
  },
  server: {
    port,
    host: "0.0.0.0",
    allowedHosts: true,
    fs: {
      strict: true,
      deny: ["**/.*"],
    },
  },
  preview: {
    port,
    host: "0.0.0.0",
    allowedHosts: true,
  },
});
